### ISSUE TITLE
(not an issue)

### ISSUE THREAD

**Issue by nilsmartel** [rafalbromirski/vim-aurora#1]
I just wanted to say that this is one of the most readable and sane looking themes I've used in a while. Thanks for the good work, I appreciate it and wanted to say that

**Comment by nilsmartel** [comment]
@rafalbromirski closing this again

**Comment by rafalbromirski** [comment]
Great to hear @nilsmartel! Enjoy.

**Comment by toddyamakawa** [comment]
@rafalbromirski, I want to reiterate what @nilsmartel said. I've tried dozens of colorschemes over the years only to switch back to jellybeans because it's the only one that looked good enough. I finally found one that looks like it might be better. Thank you!
