### ISSUE TITLE
Cursor over Parenthesis (opinion)

### ISSUE THREAD

**Issue by nilsmartel** [rafalbromirski/vim-aurora#4]
When the cursor's hovering over parenthesis it looks like the cursor sits on the enclosing end of it, instead at it's actual position.

Here's a picture to demonstrate
![Bildschirmfoto 2020-05-22 um 11 44 50](https://user-images.githubusercontent.com/28377948/82654925-b69fc800-9c21-11ea-8ebc-2112cd6860b2.png)

(the cursor sits where the arrow points, but it looks like it's on the other end of the parenthesis)

**Comment by rafalbromirski** [comment]
Good catch! 

- bd28ad0 fixes it

#### Preview:

![image](https://user-images.githubusercontent.com/130297/82657242-56128a00-9c25-11ea-9c7b-e95c8a0a9365.png)

**Comment by nilsmartel** [comment]
Quickest response I ever saw. looks great 👍

**Comment by imacross** [comment]
I am in the current version but the same problem has to me. 
![,](https://user-images.githubusercontent.com/30753807/84940973-564d5a80-b0e9-11ea-9a75-cb475e5607fe.jpg)
